---
- hosts: bridge-box
  vars:
    target_user: vagrant
    meesign_server_version: v0.2.0
  roles:
    - env-setup
    - meesign-client
    - meesign-server
    - firefox
    - webeid
    - meesign-virtual-card
    - bridge-suite
    - cleanup
