- name: Install build requirements for WebEid
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - lsb-release
    - fakeroot
    - build-essential
    - devscripts
    - cdbs
    - pkg-config
    - cmake
    - libpcsclite-dev
    - libssl-dev
    - libgtest-dev
    - libgl-dev
    - libqt6svg6-dev
    - qt6-tools-dev
    - qt6-tools-dev-tools
    - qt6-l10n-tools
    - libqt6core5compat6-dev
