---
- name: Pull MeeSign server Docker image
  become: true
  community.general.docker_image:
    name: crocsmuni/meesign:{{ meesign_server_docker_version }}
    source: pull

- name: Run meesign server
  become: true
  community.general.docker_container:
    name: meesign_server
    image: crocsmuni/meesign:{{ meesign_server_docker_version }}
    state: started
    detach: yes
    restart_policy: always
    published_ports:
      - "1337:1337"
    env:
      RUST_LOG: "warn,meesign_server=debug"
    volumes:
      - "/home/{{ target_user }}/Desktop/meesign-server/keys:/meesign/keys/"
