name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - wiki/**
      - .github/workflows/wiki.yaml
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Stripping file extensions...
        uses: impresscms-dev/strip-markdown-extensions-from-links-action@v1.0.0
        with:
          path: ./wiki/
      - run: cat ./wiki/Home.md
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          preprocess: false
